/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe.gui;

import cafe.gui.mdi.IfDiscount;
import cafe.gui.mdi.IfInventory;
import cafe.gui.mdi.IfUser;
import cafe.gui.mdi.IfMenu;
import cafe.gui.mdi.IfStaff;
import cafe.tool.MsgBox;
import cafe.tool.MyDb;

/**
 *
 * @author edwinnersherlim
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminDP = new javax.swing.JDesktopPane();
        adMenuBar = new javax.swing.JMenuBar();
        menuAction = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        miDiscounts = new javax.swing.JMenuItem();
        miInventory = new javax.swing.JMenuItem();
        miMenus = new javax.swing.JMenuItem();
        miSeparator = new javax.swing.JPopupMenu.Separator();
        miStaffs = new javax.swing.JMenuItem();
        miUsers = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        miSales = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setLocationByPlatform(true);

        javax.swing.GroupLayout adminDPLayout = new javax.swing.GroupLayout(adminDP);
        adminDP.setLayout(adminDPLayout);
        adminDPLayout.setHorizontalGroup(
            adminDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        adminDPLayout.setVerticalGroup(
            adminDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );

        menuAction.setText("Action");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        menuAction.add(miLogout);

        adMenuBar.add(menuAction);

        menuManage.setText("Manage");

        miDiscounts.setText("Discounts");
        miDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDiscountsActionPerformed(evt);
            }
        });
        menuManage.add(miDiscounts);

        miInventory.setText("Inventory");
        miInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miInventoryActionPerformed(evt);
            }
        });
        menuManage.add(miInventory);

        miMenus.setText("Menus");
        miMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMenusActionPerformed(evt);
            }
        });
        menuManage.add(miMenus);
        menuManage.add(miSeparator);

        miStaffs.setText("Staffs");
        miStaffs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStaffsActionPerformed(evt);
            }
        });
        menuManage.add(miStaffs);

        miUsers.setText("Users");
        miUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUsersActionPerformed(evt);
            }
        });
        menuManage.add(miUsers);

        adMenuBar.add(menuManage);

        menuReport.setText("Report");

        miSales.setText("Sales");
        miSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalesActionPerformed(evt);
            }
        });
        menuReport.add(miSales);

        adMenuBar.add(menuReport);

        setJMenuBar(adMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDP)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStaffsActionPerformed
        // show staff management form
        IfStaff staffChildForm = new IfStaff();
        adminDP.add(staffChildForm);
        staffChildForm.setVisible(true);
    }//GEN-LAST:event_miStaffsActionPerformed

    private void miUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUsersActionPerformed
        // show user management form
        IfUser userChildForm = new IfUser();
        adminDP.add(userChildForm);
        userChildForm.setVisible(true);
    }//GEN-LAST:event_miUsersActionPerformed

    private void miMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMenusActionPerformed
        // show menu management form
        IfMenu Menu = new IfMenu();
        adminDP.add(Menu);
        Menu.setVisible(true);
    }//GEN-LAST:event_miMenusActionPerformed

    private void miInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInventoryActionPerformed
        // show inventory management form
        IfInventory INV = new IfInventory();
        adminDP.add(INV);
        INV.setVisible(true);
    }//GEN-LAST:event_miInventoryActionPerformed

    private void miDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDiscountsActionPerformed
        // show discount management form
        IfDiscount Disc = new IfDiscount();
        adminDP.add(Disc);
        Disc.setVisible(true);
    }//GEN-LAST:event_miDiscountsActionPerformed

    private void miSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalesActionPerformed
        // show sales report based on date choosen
        new Sales(this).setVisible(true);
    }//GEN-LAST:event_miSalesActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // hide form and shows login form
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_miLogoutActionPerformed

    public void setDateShowReport(java.util.Date dateFrom, java.util.Date dateTo, String filename) {
//        MsgBox.info(new java.sql.Date(dateFrom.getTime()).toString(), new java.sql.Date(dateTo.getTime()).toString());
//        return;
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        MyDb.createSales(new java.sql.Date(dateFrom.getTime()).toString(), new java.sql.Date(dateTo.getTime()).toString(), filename);
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar adMenuBar;
    private javax.swing.JDesktopPane adminDP;
    private javax.swing.JMenu menuAction;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem miDiscounts;
    private javax.swing.JMenuItem miInventory;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miMenus;
    private javax.swing.JMenuItem miSales;
    private javax.swing.JPopupMenu.Separator miSeparator;
    private javax.swing.JMenuItem miStaffs;
    private javax.swing.JMenuItem miUsers;
    // End of variables declaration//GEN-END:variables
}
