/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cafe.gui;

import cafe.tool.MsgBox;
import cafe.tool.MyDb;

/**
 *
 * @author e
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labLogin = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnSubmit = new javax.swing.JButton();
        labId = new javax.swing.JLabel();
        labPass = new javax.swing.JLabel();
        labBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(415, 570));
        getContentPane().setLayout(null);

        labLogin.setFont(new java.awt.Font("DejaVu Sans", 1, 28)); // NOI18N
        labLogin.setForeground(new java.awt.Color(255, 51, 204));
        labLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labLogin.setText("MAID CAFE");
        getContentPane().add(labLogin);
        labLogin.setBounds(240, 540, 174, 33);

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });
        getContentPane().add(tfID);
        tfID.setBounds(230, 430, 174, 27);

        tfPassword.setText("");
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfPassword);
        tfPassword.setBounds(230, 480, 174, 27);

        btnSubmit.setMnemonic('s');
        btnSubmit.setText("Submit");
        btnSubmit.setSelected(true);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(330, 510, 74, 27);

        labId.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labId.setText("Username");
        getContentPane().add(labId);
        labId.setBounds(330, 410, 72, 15);

        labPass.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labPass.setText("Password");
        getContentPane().add(labPass);
        labPass.setBounds(330, 460, 70, 15);

        labBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/maidnontrsnaprent.png"))); // NOI18N
        getContentPane().add(labBackground);
        labBackground.setBounds(0, 0, 450, 590);

        setSize(new java.awt.Dimension(415, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // check password equality
        this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.WAIT_CURSOR));
        // check if textfield is empty
        if(tfID.getText().length() == 0 || tfPassword.getPassword().length == 0){
            this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));
            MsgBox.info("Please fill username/password");
            return;
        }

        String pass = MyDb.GetField("SELECT `Password` FROM `Login` WHERE `Username`='" + tfID.getText() + "'");
//        MsgBox.info(pass);
        if(pass.equals(tfPassword.getText())){
            String pos = MyDb.GetField("SELECT s.position FROM `Login` l JOIN `Staff` s " +
                    "ON l.id=s.user_id WHERE `Username`='" + tfID.getText() + "'");
            String sid = MyDb.GetField("SELECT s.id FROM `Login` l JOIN `Staff` s " +
                    "ON l.id=s.user_id WHERE `Username`='" + tfID.getText() + "'");
//            MsgBox.info(pos);
            this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));
            this.dispose();
            switch(pos){
                case "Admin" :
                    new Admin().setVisible(true);
                    break;
                case "Cashier" :
                    new Cashier().setVisible(true);
                    break;
                case "Chef" :
                    new Kitchen().setVisible(true);
                    break;
                case "Inventory Manager" :
                    new Inventory().setVisible(true);
                    break;
                case "Waiter" :
                    new Waiter(sid).setVisible(true);
                    break;
            }
        }
        else {
            this.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.DEFAULT_CURSOR));
            MsgBox.info("Username / Password do not match.");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // catch enter key pressed
        btnSubmitActionPerformed(evt);
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // catch enter key pressed
        btnSubmitActionPerformed(evt);
    }//GEN-LAST:event_tfIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel labBackground;
    private javax.swing.JLabel labId;
    private javax.swing.JLabel labLogin;
    private javax.swing.JLabel labPass;
    private javax.swing.JTextField tfID;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
