/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cafe.gui.mdi;

/**
 *
 * @author edwinnersherlim
 */

import cafe.tool.MyDb;

public class IfInventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifInventory
     */
    public IfInventory() {
        initComponents();
        refreshList();
    }
    private String query;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spInventory = new javax.swing.JScrollPane();
        tabInventory = new javax.swing.JTable();
        editPanelGroup = new javax.swing.JPanel();
        labUnitDesc = new javax.swing.JLabel();
        labStockDesc = new javax.swing.JLabel();
        textUnitDesc = new javax.swing.JTextField();
        labName = new javax.swing.JLabel();
        textUnitStock = new javax.swing.JTextField();
        labUnit = new javax.swing.JLabel();
        labUnitStock = new javax.swing.JLabel();
        textStockDesc = new javax.swing.JTextField();
        textUnit = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Manage Inventory");

        tabInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabInventory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabInventory.getTableHeader().setReorderingAllowed(false);
        //tabStaff = MyDb.setTable("SELECT * FROM Staff");
        spInventory.setViewportView(tabInventory);

        editPanelGroup.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        labUnitDesc.setText("Unit Description");

        labStockDesc.setText("Stock Description");

        labName.setText("Name");

        labUnit.setText("Unit");

        labUnitStock.setText("Unit / Stock");

        javax.swing.GroupLayout editPanelGroupLayout = new javax.swing.GroupLayout(editPanelGroup);
        editPanelGroup.setLayout(editPanelGroupLayout);
        editPanelGroupLayout.setHorizontalGroup(
            editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelGroupLayout.createSequentialGroup()
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labUnit)
                    .addComponent(labName))
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textName, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(textUnit, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelGroupLayout.createSequentialGroup()
                        .addComponent(labUnitDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textUnitDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(editPanelGroupLayout.createSequentialGroup()
                        .addComponent(labUnitStock)
                        .addGap(47, 47, 47)
                        .addComponent(textUnitStock, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(labStockDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textStockDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
        );
        editPanelGroupLayout.setVerticalGroup(
            editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelGroupLayout.createSequentialGroup()
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUnit)
                    .addComponent(textUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labStockDesc)
                .addComponent(textStockDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labUnitStock)
                .addComponent(textUnitStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(editPanelGroupLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(editPanelGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labUnitDesc)
                    .addComponent(textUnitDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spInventory, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editPanelGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editPanelGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // add new inventory item
        query = "INSERT INTO `Inventory` ( `Name`, `Unit` , `@unit` , `Unit_Desc` , `Stock_Desc` ) VALUES ( '" + textName.getText()+ "' , '" + textUnit.getText() + "' , '" + textUnitStock.getText() + "' , '" + textUnitDesc.getText()+ "' , '" +textStockDesc.getText() + "')"; 
//         MsgBox.info(query);
        MyDb.ExecNonQuery(query);
        clearComp();
        refreshList();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // delete inventory item
        query = "DELETE FROM `Inventory` WHERE `ID`= " + tabInventory.getValueAt(tabInventory.getSelectedRow(), 0).toString() ;
//        MsgBox.info(query);
        MyDb.ExecNonQuery(query);
        clearComp();
        refreshList();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // update inventory item
        query = "UPDATE `Inventory` SET `Name` = '" + textName.getText()+ "', `Unit`='" + textUnit.getText() + "', `@unit`='" + textUnitStock.getText() + "', `Unit_Desc`='" + textUnitDesc.getText()+ "', `Stock_Desc`='" + textStockDesc.getText() + "'";
        query += " WHERE `ID`=" + tabInventory.getValueAt(tabInventory.getSelectedRow(), 0).toString() ;
//        MsgBox.info(query);
        MyDb.ExecNonQuery(query);
        clearComp();
        refreshList();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void clearComp() {
        // clear components
        textName.setText("");
        textUnit.setText("");
        textUnitStock.setText("");
        textUnitDesc.setText("");
        textStockDesc.setText("");
    }
    
    private void refreshList() {
        // refresh table list
        tabInventory = MyDb.setTable("SELECT * FROM `Inventory` ORDER BY `Name`");
        spInventory.setViewportView(tabInventory);
        
        // set selection change event for table tabRecipe
        tabInventory.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent ev) {
                if (ev.getValueIsAdjusting())
                    return;
//                MsgBox.info("Selection Changed", "Info");
                // set textfields binding
                textName.setText(tabInventory.getValueAt(tabInventory.getSelectedRow(), 1).toString());
                textUnit.setText(tabInventory.getValueAt(tabInventory.getSelectedRow(), 2).toString());
                textUnitStock.setText(tabInventory.getValueAt(tabInventory.getSelectedRow(), 3).toString());
                textUnitDesc.setText(tabInventory.getValueAt(tabInventory.getSelectedRow(), 4).toString());
                textStockDesc.setText(tabInventory.getValueAt(tabInventory.getSelectedRow(), 5).toString());
            }
        });
    }
                
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JPanel editPanelGroup;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labStockDesc;
    private javax.swing.JLabel labUnit;
    private javax.swing.JLabel labUnitDesc;
    private javax.swing.JLabel labUnitStock;
    private javax.swing.JScrollPane spInventory;
    private javax.swing.JTable tabInventory;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textStockDesc;
    private javax.swing.JTextField textUnit;
    private javax.swing.JTextField textUnitDesc;
    private javax.swing.JTextField textUnitStock;
    // End of variables declaration//GEN-END:variables
}
